### ISSUE TITLE
Crash on rename controller

### ISSUE THREAD

**Issue by Pitometsu** [jcrisp/rails_refactor#9]
```
$ rails_refactor rename user_controller users_controller
mv: cannot stat ‘app/models/user_controller.rb’: No such file or directory
~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor.rb:85:in `read': No such file or directory @ rb_sysopen - app/models/users_controller.rb (Errno::ENOENT)
    from ~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor.rb:85:in `replace_in_file'
    from ~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor.rb:20:in `model_rename'
    from ~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor.rb:104:in `<top (required)>'
    from ~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor:2:in `load'
    from ~/CurrentProject/.bundle/ruby/2.2.0/gems/rails_refactor-1.3/bin/rails_refactor:2:in `<top (required)>'
    from ~/CurrentProject/.bundle/bin/rails_refactor:16:in `load'
    from ~/CurrentProject/.bundle/bin/rails_refactor:16:in `<main>'
```

```
$ rails --version
Rails 4.2.4
$ ruby --version
ruby 2.2.2p133 (2015-06-12) [x86_64-linux]
$ bundler --version
Bundler version 1.7.9
$ echo $GEM_HOME
~/CurrentProject/.bundle/ruby/2.2.0
```

**Comment by jcrisp** [comment]
Hi @Pitometsu, sorry for the belated response. I'm now actively maintaining the gem again. I've made some updates for rails 4, I think this will work for you now.
Cheers
James
